services:

  dbbackup:
    build:
      context: .
      dockerfile: Dockerfile
    image: cuongnb14/db-backup:pg16-1.0
    container_name: dbbackup
    environment:
      PG_HOST: devhost
      PG_PORT: 5432
      PG_USER: dev
      PG_PASSWORD: dev
      PG_SSLMODE: disable
    volumes:
      - ./backup:/backup
      - ./config.yaml:/app/config.yaml
